const STYLE = 'flat children\'s book illustration style, warm cheerful colors, simple clean background, no text in image'

export const BOOKS = [
  // ─── Ages 3-5 ───
  {
    id: 'hungry-caterpillar',
    title: 'The Very Hungry Caterpillar',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `A cute smiling green caterpillar on a bright red apple, one tiny hole bitten out, ${STYLE}`,
    pagePrompts: [
      `A tiny white speckled egg resting on a bright green leaf, warm morning sunlight, ${STYLE}`,
      `A cute smiling green caterpillar eating through the middle of a round red apple, ${STYLE}`,
      `A green caterpillar eating through colorful fruits in a row: orange, purple plum, red strawberry, blue blueberries, ${STYLE}`,
      `A green caterpillar surrounded by lots of food: chocolate cake, ice cream, pickle, sausage, cupcake, ${STYLE}`,
      `A round fat green caterpillar lying on a leaf looking uncomfortable, holding its tummy, ${STYLE}`,
      `A green caterpillar spinning and wrapping itself in a brown cocoon on a tree branch, ${STYLE}`,
      `A beautiful colorful butterfly with bright patterned wings emerging from a cocoon, wings spread wide, ${STYLE}`,
    ],
  },
  {
    id: 'goldilocks',
    title: 'Goldilocks and the Three Bears',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `A cute blonde girl with curly hair standing in front of a cozy forest cottage, three friendly bears visible inside, ${STYLE}`,
    pagePrompts: [
      `Three friendly bears family - big papa bear, medium mama bear, tiny baby bear - walking away from their cozy cottage in morning light, ${STYLE}`,
      `A cute blonde curly-haired girl peeking through the door of a cozy little cottage in the woods, ${STYLE}`,
      `A cute blonde girl tasting porridge from a tiny bowl at a wooden table with three bear-sized bowls, ${STYLE}`,
      `A cute blonde girl sitting in a tiny wooden chair that is cracking and breaking beneath her, surprised expression, ${STYLE}`,
      `A cute blonde girl sleeping peacefully in a small cozy bed with a patchwork quilt, soft bedroom light, ${STYLE}`,
      `Three surprised bears standing in their bedroom doorway looking at sleeping girl, ${STYLE}`,
      `A cute blonde girl jumping out of bed with surprised expression, three bears watching kindly, cozy cottage bedroom, ${STYLE}`,
    ],
  },
  {
    id: 'three-pigs',
    title: 'The Three Little Pigs',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Three cute cartoon pink pigs each holding building materials - straw, sticks, and bricks - smiling cheerfully, ${STYLE}`,
    pagePrompts: [
      `Three cute pink piglets waving goodbye to their mother pig, setting off on an adventure, sunny day, ${STYLE}`,
      `A cute pink pig happily building a house made of golden straw, ${STYLE}`,
      `A cute pink pig building a house made of wooden sticks and logs, ${STYLE}`,
      `A cute pink pig carefully laying red bricks to build a strong house, ${STYLE}`,
      `A big grey wolf huffing and puffing at a straw house, straw flying everywhere, scared pig inside, ${STYLE}`,
      `A big grey wolf blowing hard at a stick house falling apart, two scared pigs running, ${STYLE}`,
      `Three pigs safe inside a sturdy brick house, wolf outside looking defeated, chimney with warm smoke, ${STYLE}`,
    ],
  },
  {
    id: 'red-riding-hood',
    title: 'Little Red Riding Hood',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `A cute little girl in a bright red hooded cape walking through a sunny green forest carrying a wicker basket, ${STYLE}`,
    pagePrompts: [
      `A cute girl in a red hooded cape receiving a basket of goodies from her mother at a cottage door, sunny day, ${STYLE}`,
      `A cute girl in red cape skipping happily through a colorful sunny forest with tall green trees, ${STYLE}`,
      `A cute girl in red cape meeting a friendly-looking wolf on a forest path, both smiling politely, ${STYLE}`,
      `A cute girl in red cape knocking on grandmother's cozy cottage door, flowers around the entrance, ${STYLE}`,
      `A cute girl in red cape looking surprised at grandmother's bed with the wolf dressed in grandmother's clothes and bonnet, ${STYLE}`,
      `A brave woodcutter arriving at grandmother's cottage, wolf looking scared, ${STYLE}`,
      `The cute girl, grandmother and woodcutter all sitting together happily having tea, wolf gone, cozy cottage, ${STYLE}`,
    ],
  },
  {
    id: 'gingerbread-man',
    title: 'The Gingerbread Man',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `A cute smiling gingerbread man cookie with icing buttons and a big smile, running happily, warm bakery background, ${STYLE}`,
    pagePrompts: [
      `A smiling gingerbread man cookie jumping out of a warm oven in a cozy kitchen, surprised baker and wife, ${STYLE}`,
      `A cheerful gingerbread man running down a country lane past surprised farm animals, ${STYLE}`,
      `A gingerbread man running past a surprised farmer with a pitchfork in a field, ${STYLE}`,
      `A gingerbread man running past a surprised fox sitting by a river, both looking at each other, ${STYLE}`,
      `A gingerbread man talking to a clever-looking fox beside a wide river, ${STYLE}`,
      `A gingerbread man riding on the nose of a smiling fox crossing a river, ${STYLE}`,
      `A gingerbread man crumbling at the edge of river, fox looking sly, chase is over, ${STYLE}`,
    ],
  },
  {
    id: 'billy-goats',
    title: 'The Three Billy Goats Gruff',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Three cute cartoon goats of different sizes standing on a wooden bridge, friendly grumpy troll below in the water, ${STYLE}`,
    pagePrompts: [
      `Three cute goats of different sizes looking longingly at lush green grass across a wooden bridge, ${STYLE}`,
      `A tiny cute goat crossing a wooden bridge over a sparkling stream, friendly looking troll peeking from below, ${STYLE}`,
      `A medium-sized cute goat crossing the wooden bridge, troll popping up with silly expression, ${STYLE}`,
      `A big strong goat facing a funny-looking troll on a wooden bridge, goat lowering horns, ${STYLE}`,
      `A big strong goat butting a troll off a bridge with a big splash, ${STYLE}`,
      `Three happy goats eating lush green grass together on the hillside, ${STYLE}`,
      `Three happy goats looking back across the bridge at a grumpy but harmless troll, all peaceful, ${STYLE}`,
    ],
  },

  // ─── Ages 5-8 ───
  {
    id: 'cat-in-hat',
    title: 'The Cat in the Hat',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `A tall anthropomorphic cat wearing a tall red and white striped hat, holding a red umbrella, mischievous grin, original colorful flat illustration style, ${STYLE}`,
    pagePrompts: [
      `Two bored children sitting at a window watching rain fall outside on a grey rainy day, cozy house interior, ${STYLE}`,
      `A tall cat in a red and white striped hat bursting through a front door with an umbrella, two surprised children watching, ${STYLE}`,
      `The tall hat cat balancing a fishbowl and other objects on one hand while standing on a ball, children amazed, ${STYLE}`,
      `A pink fluffy creature called Thing One running around a tidy living room making chaos, children chasing, ${STYLE}`,
      `Two small furry creatures called Thing One and Thing Two flying kites indoors, string tangled everywhere, ${STYLE}`,
      `A family goldfish in a bowl looking worried at all the indoor chaos, holding up a sign, ${STYLE}`,
      `The tall hat cat using a fantastic machine with many arms to clean up the messy room quickly, ${STYLE}`,
      `Children and the cat working together to tidy up the house before mother returns, ${STYLE}`,
      `Mother arriving home to find a perfectly tidy house, children sitting reading innocently, ${STYLE}`,
      `The cat waving goodbye from the doorway, red and white hat on, walking into the sunshine, ${STYLE}`,
    ],
  },
  {
    id: 'cinderella',
    title: 'Cinderella',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `A beautiful kind girl in a shimmering blue ballgown with sparkly glass slippers, magical starlight, elegant castle silhouette, ${STYLE}`,
    pagePrompts: [
      `A kind girl in simple clothes doing chores in a cozy kitchen while two mean stepsisters lounge nearby, ${STYLE}`,
      `Royal herald reading a scroll announcing a grand royal ball, villagers gathered around excitedly, ${STYLE}`,
      `A kind girl sadly watching two glittery stepsisters leave for the ball in a fancy carriage, ${STYLE}`,
      `A glowing fairy godmother appearing in a garden surrounded by sparkles, kind girl watching in amazement, ${STYLE}`,
      `A beautiful girl transformed into a shimmering ballgown, pumpkin turned into golden carriage, mice into white horses, ${STYLE}`,
      `A beautiful girl dancing gracefully with a handsome prince in a grand ballroom full of sparkling chandeliers, ${STYLE}`,
      `A beautiful girl running away at midnight, one glass slipper left on grand marble palace steps, ${STYLE}`,
      `A prince kneeling holding a glass slipper, searching through the kingdom, determined expression, ${STYLE}`,
      `A prince placing a glass slipper on a girl's foot, it fits perfectly, both smiling with joy, ${STYLE}`,
      `A beautiful royal wedding with happy couple, fairy godmother watching, stepsisters surprised, ${STYLE}`,
    ],
  },
  {
    id: 'snow-white',
    title: 'Snow White',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `A kind girl with dark short hair and red lips surrounded by seven small cheerful dwarfs in a forest clearing, ${STYLE}`,
    pagePrompts: [
      `A kind queen making a wish at a snowy window, a single red rose, cozy winter castle scene, ${STYLE}`,
      `A young girl with dark hair and red lips, kind face, living in a grand castle with a jealous queen, ${STYLE}`,
      `A huntsman in a forest letting a scared girl run free, compassionate expression, forest background, ${STYLE}`,
      `A girl with dark hair discovering a tiny cozy cottage in the forest, seven small beds inside, ${STYLE}`,
      `Seven small cheerful dwarfs returning home, finding girl asleep in their cottage, surprised expressions, ${STYLE}`,
      `A jealous queen disguised as an old woman offering a shiny red apple to a trusting girl, cottage doorway, ${STYLE}`,
      `Seven dwarfs sadly placing a girl in a beautiful glass case in the forest, flowers around, ${STYLE}`,
      `A handsome prince discovering a girl in a glass case in the forest, amazed expression, ${STYLE}`,
      `A prince kneeling by a girl who is waking up, seven dwarfs cheering around them, golden light, ${STYLE}`,
      `A happy royal wedding with the girl, prince, and seven cheerful dwarfs celebrating together, ${STYLE}`,
    ],
  },
  {
    id: 'hansel-gretel',
    title: 'Hansel and Gretel',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `A boy and girl discovering a magical house made entirely of candy, cookies, and sweets in a forest, eyes wide with wonder, ${STYLE}`,
    pagePrompts: [
      `A boy and girl listening sadly as parents talk worriedly at a kitchen table, cozy poor cottage, ${STYLE}`,
      `Two children being led into a dark dense forest by sad parents, leaving white pebbles on path, ${STYLE}`,
      `Two children alone in a dark forest, boy dropping breadcrumbs along the path, ${STYLE}`,
      `Two children sleeping under a tree, birds eating all the breadcrumbs from the path, ${STYLE}`,
      `Two amazed children discovering a magical gingerbread house decorated with candy and icing in the forest, ${STYLE}`,
      `An old witch with a friendly disguise welcoming two children into her candy house, ${STYLE}`,
      `A boy locked in a cage by a witch, his sister forced to cook and clean, determined expression, ${STYLE}`,
      `A brave girl pushing a witch into a large oven, flames visible, witch looking shocked, ${STYLE}`,
      `Two children finding chests of jewels and gold in the witch's cottage, celebrating, ${STYLE}`,
      `Two happy children reunited with their grateful parents at a cozy cottage door, chests of treasure, ${STYLE}`,
    ],
  },
  {
    id: 'jack-beanstalk',
    title: 'Jack and the Beanstalk',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `A brave boy climbing an enormous twisting green beanstalk that reaches into magical clouds, a castle visible above, ${STYLE}`,
    pagePrompts: [
      `A boy leading a thin cow down a country road, poor farm cottage in background, ${STYLE}`,
      `A boy trading a cow for five colorful magical beans from a mysterious old man, ${STYLE}`,
      `An enormous magical beanstalk growing overnight through bedroom ceiling reaching into the clouds, boy amazed, ${STYLE}`,
      `A boy climbing a giant green beanstalk surrounded by clouds, excited expression, tiny farm below, ${STYLE}`,
      `A boy arriving at a magnificent huge castle in the clouds above the beanstalk, ${STYLE}`,
      `A giant's wife hiding a small boy in a large cooking pot as giant arrives home, ${STYLE}`,
      `A giant sitting at an enormous table counting gold coins, small boy hiding and watching, ${STYLE}`,
      `A boy running with a giant golden harp under his arm, giant chasing behind, ${STYLE}`,
      `A boy chopping down the enormous beanstalk with an axe, giant falling, mother watching, ${STYLE}`,
      `A boy and mother celebrating with gold coins and golden harp, happy ending at cozy cottage, ${STYLE}`,
    ],
  },
  {
    id: 'rapunzel',
    title: 'Rapunzel',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `A girl with enormously long golden hair hanging from a tall stone tower window, a prince standing below looking up, ${STYLE}`,
    pagePrompts: [
      `A couple stealing glowing rapunzel herbs from a witch's magical garden at night, ${STYLE}`,
      `A witch taking a baby girl from a frightened couple in exchange for the stolen herbs, ${STYLE}`,
      `A girl with very long golden hair living alone in a tall stone tower in the forest, ${STYLE}`,
      `A witch climbing up enormously long golden hair to reach the top of a tall tower, ${STYLE}`,
      `A handsome prince riding his horse, discovering a tall tower in the forest, hearing beautiful singing, ${STYLE}`,
      `A handsome prince climbing up long golden hair to reach a girl in a tower, amazed to see her, ${STYLE}`,
      `A girl and prince talking happily at tower window, planning escape, golden hair flowing, ${STYLE}`,
      `An angry witch cutting a girl's long golden hair with scissors, girl shocked and sad, ${STYLE}`,
      `A prince wandering blind in a desert, crying, golden-haired girl appearing before him, ${STYLE}`,
      `A girl and prince reunited in a beautiful kingdom, her magical tears healing his eyes, joyful embrace, ${STYLE}`,
    ],
  },
]

export function getBook(id) {
  return BOOKS.find(b => b.id === id) ?? null
}
