const STYLE = 'simple flat children\'s illustration style, consistent warm colors, white or simple background, no text in image'

export const BOOKS = [
  // ─── Ages 3-5 ───
  {
    id: 'hungry-caterpillar',
    title: 'The Very Hungry Caterpillar',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Children's book illustration of a very cute smiling green caterpillar on a bright red apple, colorful flat illustration style, white background, warm cheerful colors`,
    pagePrompts: [
      `A tiny white speckled egg resting on a bright green leaf in gentle morning light, ${STYLE}`,
      `A very small green caterpillar hatching from the egg and looking around on the leaf, ${STYLE}`,
      `A cute green caterpillar taking one bite from a red apple, one small hole visible, ${STYLE}`,
      `A green caterpillar eating through a row of simple colorful fruits: pear, plum, strawberry, orange, ${STYLE}`,
      `A green caterpillar nibbling many treats on a table, then looking a little sleepy and full, ${STYLE}`,
      `A big round green caterpillar wrapping itself in a brown cocoon hanging from a branch, ${STYLE}`,
      `A beautiful colorful butterfly with bright patterned wings spreading its wings after emerging, ${STYLE}`,
    ],
  },
  {
    id: 'goldilocks',
    title: 'Goldilocks and the Three Bears',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Children's book illustration of a cute blonde girl with curly hair standing in front of a cozy cottage in the woods, three bears visible through window, flat warm illustration style`,
    pagePrompts: [
      `Three bears walking together in the forest near their cozy cottage, ${STYLE}`,
      `A cute blonde girl with curly hair noticing a small cottage in the woods, ${STYLE}`,
      `The girl stepping inside and seeing three bowls of porridge on a table, ${STYLE}`,
      `The girl tasting the small bowl of porridge and smiling because it is just right, ${STYLE}`,
      `The girl sitting on a small chair and the chair breaking gently, the girl surprised, ${STYLE}`,
      `The girl asleep in the smallest bed under a cozy quilt, ${STYLE}`,
      `Three bears returning home and finding the girl, everyone surprised but calm, ${STYLE}`,
    ],
  },
  {
    id: 'three-pigs',
    title: 'The Three Little Pigs',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Children's book illustration of three cute cartoon pigs each holding building materials, straw hay bricks and sticks, colorful flat style, warm cheerful`,
    pagePrompts: [
      `Three little pigs saying goodbye and walking down a sunny path to build homes, ${STYLE}`,
      `The first pig building a small straw house, stacks of straw nearby, ${STYLE}`,
      `The second pig building a small stick house, bundles of sticks nearby, ${STYLE}`,
      `The third pig building a strong brick house, neat red bricks stacked, ${STYLE}`,
      `A wolf blowing at the straw house while the first pig runs away, straw flying, ${STYLE}`,
      `A wolf blowing at the stick house while two pigs run toward the brick house, sticks scattering, ${STYLE}`,
      `All three pigs safe inside the brick house while the wolf looks tired outside, ${STYLE}`,
    ],
  },
  {
    id: 'red-riding-hood',
    title: 'Little Red Riding Hood',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Children's book illustration of a cute little girl in a red hooded cape walking through a sunny forest with a basket, flat warm illustration style`,
    pagePrompts: [
      `A mother giving a basket to a girl in a red hood at the cottage door, ${STYLE}`,
      `The girl walking along a sunny forest path holding the basket, ${STYLE}`,
      `The girl meeting a wolf on the path, the wolf smiling politely from a distance, ${STYLE}`,
      `The girl arriving at a small cottage in the woods with flowers outside, ${STYLE}`,
      `The girl standing by a bed with a wolf pretending to be grandmother, cozy room, ${STYLE}`,
      `A helpful woodcutter coming to the cottage doorway, the wolf startled, ${STYLE}`,
      `The girl and grandmother safe together in the cottage, calm happy ending scene, ${STYLE}`,
    ],
  },
  {
    id: 'gingerbread-man',
    title: 'The Gingerbread Man',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Children's book illustration of a cute smiling gingerbread man running happily, colorful flat style, warm bakery background`,
    pagePrompts: [
      `A gingerbread man jumping out of an oven tray in a cozy kitchen, ${STYLE}`,
      `The gingerbread man running out the door while people chase behind, ${STYLE}`,
      `The gingerbread man running past a cow and a horse in a field, animals surprised, ${STYLE}`,
      `The gingerbread man reaching a wide river and looking worried, ${STYLE}`,
      `A clever fox offering to help the gingerbread man cross the river, ${STYLE}`,
      `The gingerbread man riding on the fox's back across the river, water gently flowing, ${STYLE}`,
      `The gingerbread man reaching the fox's nose near the far bank, tense moment, ${STYLE}`,
    ],
  },
  {
    id: 'billy-goats',
    title: 'The Three Billy Goats Gruff',
    ageGroup: '3-5',
    pageCount: 7,
    coverPrompt: `Children's book illustration of three cute cartoon goats on a wooden bridge over a stream, friendly troll below, flat warm illustration style`,
    pagePrompts: [
      `Three goats looking at a green hill across a wooden bridge over a stream, ${STYLE}`,
      `The smallest goat stepping onto the wooden bridge, a troll peeking from below, ${STYLE}`,
      `The middle goat crossing the bridge while the troll looks up from under it, ${STYLE}`,
      `The biggest goat standing bravely on the bridge facing the troll, ${STYLE}`,
      `The biggest goat chasing the troll away from the bridge, the troll stumbling back, ${STYLE}`,
      `All three goats eating lush green grass on the far hillside, peaceful scene, ${STYLE}`,
      `The three goats smiling together on the grassy hill with the bridge in the distance, ${STYLE}`,
    ],
  },

  // ─── Ages 5-8 ───
  {
    id: 'cat-in-hat',
    title: 'The Cat in the Hat',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `Children's book illustration of a tall cat wearing a red and white striped hat, holding an umbrella, flat colorful illustration style, Dr Seuss inspired but original`,
    pagePrompts: [
      `Two bored children sitting at a window watching rain fall outside on a grey rainy day, cozy house interior, ${STYLE}`,
      `A tall cat in a red and white striped hat bursting through a front door with an umbrella, two surprised children watching, ${STYLE}`,
      `The tall hat cat balancing a fishbowl and other objects on one hand while standing on a ball, children amazed, ${STYLE}`,
      `A pink fluffy creature called Thing One running around a tidy living room making chaos, children chasing, ${STYLE}`,
      `Two small furry creatures called Thing One and Thing Two flying kites indoors, string tangled everywhere, ${STYLE}`,
      `A family goldfish in a bowl looking worried at all the indoor chaos, splashes around the bowl, ${STYLE}`,
      `The tall hat cat using a fantastic machine with many arms to clean up the messy room quickly, ${STYLE}`,
      `Children and the cat working together to tidy up the house before mother returns, ${STYLE}`,
      `Mother arriving home to find a perfectly tidy house, children sitting reading innocently, ${STYLE}`,
      `The cat waving goodbye from the doorway, red and white hat on, walking into the sunshine, ${STYLE}`,
    ],
  },
  {
    id: 'cinderella',
    title: 'Cinderella',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `Children's book illustration of a beautiful girl in a blue ballgown with glass slippers, magical sparkles, castle in background, flat warm illustration style`,
    pagePrompts: [
      `A kind girl in simple clothes doing chores in a cozy kitchen while two mean stepsisters lounge nearby, ${STYLE}`,
      `Royal herald reading a scroll announcing a grand royal ball, villagers gathered around excitedly, ${STYLE}`,
      `A kind girl sadly watching two glittery stepsisters leave for the ball in a fancy carriage, ${STYLE}`,
      `A glowing fairy godmother appearing in a garden surrounded by sparkles, kind girl watching in amazement, ${STYLE}`,
      `A beautiful girl transformed into a shimmering ballgown, pumpkin turned into golden carriage, mice into white horses, ${STYLE}`,
      `A beautiful girl dancing gracefully with a handsome prince in a grand ballroom full of sparkling chandeliers, ${STYLE}`,
      `A beautiful girl running away at midnight, one glass slipper left on grand marble palace steps, ${STYLE}`,
      `A prince kneeling holding a glass slipper, searching through the kingdom, determined expression, ${STYLE}`,
      `A prince placing a glass slipper on a girl's foot, it fits perfectly, both smiling with joy, ${STYLE}`,
      `A beautiful royal wedding with happy couple, fairy godmother watching, stepsisters surprised, ${STYLE}`,
    ],
  },
  {
    id: 'snow-white',
    title: 'Snow White',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `Children's book illustration of a kind girl with dark hair and red lips surrounded by seven small friendly dwarfs in a forest, flat warm illustration style`,
    pagePrompts: [
      `A kind queen making a wish at a snowy window, a single red rose, cozy winter castle scene, ${STYLE}`,
      `A young girl with dark hair and red lips, kind face, living in a grand castle with a jealous queen, ${STYLE}`,
      `A huntsman in a forest letting a scared girl run free, compassionate expression, forest background, ${STYLE}`,
      `A girl with dark hair discovering a tiny cozy cottage in the forest, seven small beds inside, ${STYLE}`,
      `Seven small cheerful dwarfs returning home, finding girl asleep in their cottage, surprised expressions, ${STYLE}`,
      `A jealous queen disguised as an old woman offering a shiny red apple to a trusting girl, cottage doorway, ${STYLE}`,
      `Seven dwarfs sadly placing a girl in a beautiful glass case in the forest, flowers around, ${STYLE}`,
      `A handsome prince discovering a girl in a glass case in the forest, amazed expression, ${STYLE}`,
      `A prince kneeling by a girl who is waking up, seven dwarfs cheering around them, golden light, ${STYLE}`,
      `A happy royal wedding with the girl, prince, and seven cheerful dwarfs celebrating together, ${STYLE}`,
    ],
  },
  {
    id: 'hansel-gretel',
    title: 'Hansel and Gretel',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `Children's book illustration of a boy and girl discovering a magical candy house in the forest, flat warm colorful illustration style`,
    pagePrompts: [
      `A boy and girl listening sadly as parents talk worriedly at a kitchen table, cozy poor cottage, ${STYLE}`,
      `Two children being led into a dark dense forest by sad parents, leaving white pebbles on path, ${STYLE}`,
      `Two children alone in a dark forest, boy dropping breadcrumbs along the path, ${STYLE}`,
      `Two children sleeping under a tree, birds eating all the breadcrumbs from the path, ${STYLE}`,
      `Two amazed children discovering a magical gingerbread house decorated with candy and icing in the forest, ${STYLE}`,
      `An old witch with a friendly disguise welcoming two children into her candy house, ${STYLE}`,
      `A boy locked in a cage by a witch, his sister forced to cook and clean, determined expression, ${STYLE}`,
      `A brave girl pushing a witch into a large oven, flames visible, witch looking shocked, ${STYLE}`,
      `Two children finding chests of jewels and gold in the witch's cottage, celebrating, ${STYLE}`,
      `Two happy children reunited with their grateful parents at a cozy cottage door, chests of treasure, ${STYLE}`,
    ],
  },
  {
    id: 'jack-beanstalk',
    title: 'Jack and the Beanstalk',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `Children's book illustration of a boy climbing an enormous green beanstalk reaching into clouds, castle above, flat colorful illustration style`,
    pagePrompts: [
      `A boy leading a thin cow down a country road, poor farm cottage in background, ${STYLE}`,
      `A boy trading a cow for five colorful magical beans from a mysterious old man, ${STYLE}`,
      `An enormous magical beanstalk growing overnight through bedroom ceiling reaching into the clouds, boy amazed, ${STYLE}`,
      `A boy climbing a giant green beanstalk surrounded by clouds, excited expression, tiny farm below, ${STYLE}`,
      `A boy arriving at a magnificent huge castle in the clouds above the beanstalk, ${STYLE}`,
      `A giant's wife hiding a small boy in a large cooking pot as giant arrives home, ${STYLE}`,
      `A giant sitting at an enormous table counting gold coins, small boy hiding and watching, ${STYLE}`,
      `A boy running with a giant golden harp under his arm, giant chasing behind, ${STYLE}`,
      `A boy chopping down the enormous beanstalk with an axe, giant falling, mother watching, ${STYLE}`,
      `A boy and mother celebrating with gold coins and golden harp, happy ending at cozy cottage, ${STYLE}`,
    ],
  },
  {
    id: 'rapunzel',
    title: 'Rapunzel',
    ageGroup: '5-8',
    pageCount: 10,
    coverPrompt: `Children's book illustration of a girl with extremely long golden hair hanging from a tall tower window, prince below, flat warm illustration style`,
    pagePrompts: [
      `A couple stealing glowing rapunzel herbs from a witch's magical garden at night, ${STYLE}`,
      `A witch taking a baby girl from a frightened couple in exchange for the stolen herbs, ${STYLE}`,
      `A girl with very long golden hair living alone in a tall stone tower in the forest, ${STYLE}`,
      `A witch climbing up enormously long golden hair to reach the top of a tall tower, ${STYLE}`,
      `A handsome prince riding his horse, discovering a tall tower in the forest, hearing beautiful singing, ${STYLE}`,
      `A handsome prince climbing up long golden hair to reach a girl in a tower, amazed to see her, ${STYLE}`,
      `A girl and prince talking happily at tower window, planning escape, golden hair flowing, ${STYLE}`,
      `An angry witch cutting a girl's long golden hair with scissors, girl shocked and sad, ${STYLE}`,
      `A prince wandering blind in a desert, crying, golden-haired girl appearing before him, ${STYLE}`,
      `A girl and prince reunited in a beautiful kingdom, her magical tears healing his eyes, joyful embrace, ${STYLE}`,
    ],
  },
]

export function getBook(id) {
  return BOOKS.find(b => b.id === id) ?? null
}
