export const stories = [
  {
    id: 'pips-snowy-day',
    title: "Pip's Snowy Day",
    cover: '🐧',
    color: '#C8E6F5',
    textColor: '#1B2E4A',
    pages: [
      { text: 'One morning, Pip the Penguin woke up and peeked outside.', emoji: '🐧' },
      { text: 'Everything was white! Snow had fallen softly all through the night.', emoji: '❄️' },
      { text: 'Pip put on his favourite scarf and waddled happily outside.', emoji: '🧣' },
      { text: 'He rolled a big snowball down the hill. Wheee!', emoji: '⛄' },
      { text: 'His friends came out to play too. Everyone laughed and laughed.', emoji: '🎉' },
      { text: 'They played all day until the stars began to appear.', emoji: '🌟' },
      { text: 'Pip went home, warm and cosy. What a perfect snowy day.', emoji: '💙' },
    ],
  },
  {
    id: 'the-sleepy-star',
    title: 'The Sleepy Star',
    cover: '⭐',
    color: '#1B2E4A',
    textColor: '#FFFDE7',
    pages: [
      { text: 'High up in the night sky lived a little star named Stella.', emoji: '⭐' },
      { text: 'Every night, Stella would shine as bright as she possibly could.', emoji: '✨' },
      { text: 'But one night, Stella felt very, very sleepy.', emoji: '😴' },
      { text: 'She yawned so wide that all the other stars looked over.', emoji: '🌟' },
      { text: 'The moon smiled gently and said, "It is okay to rest, little one."', emoji: '🌙' },
      { text: 'Stella closed her eyes and drifted off to sleep.', emoji: '💫' },
      { text: 'And while she slept, she glowed softly — the warmest light of all.', emoji: '🌌' },
    ],
  },
  {
    id: 'the-tiny-seed',
    title: 'The Tiny Seed',
    cover: '🌱',
    color: '#7DC44E',
    textColor: '#1A5C00',
    pages: [
      { text: 'A tiny seed fell gently into the soft, dark ground.', emoji: '🌱' },
      { text: 'It was very cold and very dark down there. But the seed was brave.', emoji: '🌑' },
      { text: 'Slowly, slowly, the seed began to grow.', emoji: '💪' },
      { text: 'A little green shoot pushed up through the soil to say hello.', emoji: '🌿' },
      { text: 'Then came leaves, reaching up toward the warm, golden sunshine.', emoji: '☀️' },
      { text: 'And then — a beautiful flower bloomed for the very first time!', emoji: '🌸' },
      { text: 'From one tiny seed, something wonderful had grown. Just like you.', emoji: '🌺' },
    ],
  },
]
